DEFAULT_LOG_DIR = "logs"

DEFAULT_RANDOM_SEED = 42

# learning parameters
DEFAULT_NUM_EPISODES = 500
DEFAULT_MAX_EP_STEPS = 500
DEFAULT_STEP_SIZE = 0.5
DEFAULT_DISCOUNT_FACTOR = 0.95
DEFAULT_EXPLORE_PROBABILITY = 0.1

DEFAULT_ENV_RENDER_MODES = ["human", "rgb_array", "ansi"]
